MicroBlog/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^webchat/',include('webchat.urls')),
    url(r'^blog/',include('blog.urls')),
    url(r'^', include('web.urls')),

]

web/urls.py
from django.conf.urls import url
from web.views import home
from web.views import account

urlpatterns = [
    url(r'^jsonp.html$', account.jsonp),
    url(r'^login.html$', account.login),
    url(r'^logout.html$', account.logout),
    url(r'^register.html$', account.register),
    url(r'^check_code.html$', account.check_code),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^', home.index),
]

repository/models.py
#-*- coding=utf-8 -*-
from django.db import models


class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像')
    line_status = models.BooleanField(verbose_name="是否在线",default=False)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',#自定义联系表
                                  related_name='f',
                                  through_fields=('user', 'follower'))

class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users')
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid', related_name='followers')

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]



class Blog(models.Model):
    """
    博客信息表
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    subtitle = models.CharField(verbose_name='个人博客副标题',max_length=64,default="Just do it")
    ad = models.CharField(verbose_name="个人博客公告",max_length=64,default= u"公告内容")
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid')

class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

class Tag(models.Model):
    '''
    博主个人文章标签
    '''
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')


class Article(models.Model):
    '''
    文章表
    '''
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(verbose_name="阅读数",default=0)
    comment_count = models.IntegerField(verbose_name="评论数",default=0)
    up_count = models.IntegerField(verbose_name="点赞数",default=0)
    down_count = models.IntegerField(verbose_name="点踩数",default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')
    category = models.ForeignKey(verbose_name='文章所属分类', to='Category', to_field='nid', null=True)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "计算机和网络基础"),
        (4, "网络安全"),
        (5, "其他")
    ]

    article_type_id = models.IntegerField(verbose_name="文章类型表",choices=type_choices, default=None)

    tags = models.ManyToManyField(verbose_name="文章所附标签",
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')
class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid')
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复评论', to='self', related_name='back', null=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')


class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]



class Chat(models.Model):
    content = models.TextField(verbose_name="聊天内容")
    user = models.ForeignKey(verbose_name="用户",to='UserInfo',to_field='nid')
    creat_date = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)

blog/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render,HttpResponse
from django.shortcuts import redirect
from repository import models
from utils.pagination import Pagination,Pagination2
from django.urls import reverse
import json
from django.http.request import QueryDict


def home(request, site):
    """
    博主个人首页
    :param request:
    :param site: 博主的网站后缀如：http://xxx.com/wupeiqi.html
    :return:
    """
    #获取博客对象
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    #获取该博客所有标签和分类
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    # date_format(create_time,"%Y-%m")
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%%Y-%%m",create_time) as ctime from repository_article WHERE blog_id = %s group by strftime("%%Y-%%m",create_time)'%blog.nid)
        #group by 分组,外键过滤
    #获取该博客当前页所有文章对象和分页html
    article_list_all = models.Article.objects.filter(blog=blog).order_by('-nid').all()
    p= Pagination2(request.GET.get('p',1),article_list_all.count())
    article_list=article_list_all[p.start:p.end]
    page_str = p.page_str(reverse('article_home',kwargs={'site':site}))

    #获取博客文章总数
    article_counts = article_list_all.count()




    #获取博客文章评论总数
    article_comment_counts=0
    for item in article_list:
        article_comment_counts += models.Comment.objects.filter(article=item).count()

    #获取最新评论
    recent_comments = models.Comment.objects.all().order_by("-nid")[0:5]



    return render(
        request,
        'home.html',
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list,
            'article_counts':article_counts,
            'article_comment_counts':article_comment_counts,
            'recent_comments':recent_comments,
            'page_str':page_str,
        }
    )


def filter(request, site, condition, val):
    """
    分类显示
    :param request:
    :param site:
    :param condition:
    :param val:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%%Y-%%m",create_time) as ctime from repository_article WHERE blog_id = %s group by strftime("%%Y-%%m",create_time)'%blog.nid)

    template_name = "home_summary_list.html"
    if condition == 'tag':
        article_list_all = models.Article.objects.filter(tags=val, blog=blog).all()
    elif condition == 'category':
        article_list_all = models.Article.objects.filter(category_id=val, blog=blog).all()
    elif condition == 'date':
        # article_list = models.Article.objects.filter(blog=blog).extra(
        # where=['date_format(create_time,"%%Y-%%m")=%s'], params=[val, ]).all()

        article_list_all = models.Article.objects.filter(blog=blog).extra(
            where=['strftime("%%Y-%%m",create_time)=%s'], params=[val, ]).all()
        # select * from article where strftime("%Y-%m",create_time)=2017-02
    else:
        article_list_all = []

    p = Pagination2(request.GET.get('p', 1), article_list_all.count())
    article_list = article_list_all[p.start:p.end]
    page_str = p.page_str(reverse('article_filter', kwargs={'site': site,'condition':condition,'val':val}))

    # 获取博客文章总数
    article_counts = article_list_all.count()
    # 获取博客文章评论总数
    article_comment_counts = 0
    for item in article_list:
        article_comment_counts += models.Comment.objects.filter(article=item).count()

    #获取最新评论
    recent_comments = models.Comment.objects.all().order_by("-nid")[0:5]

    return render(
        request,
        template_name,
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list,
            'article_counts': article_counts,
            'article_comment_counts': article_comment_counts,
            'recent_comments': recent_comments,
            'page_str':page_str
        }
    )


def detail(request, site, nid):
    """
    博文详细页
    :param request:
    :param site:
    :param nid:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%%Y-%%m",create_time) as ctime from repository_article WHERE blog_id = %s group by strftime("%%Y-%%m",create_time)'%blog.nid)


    comment_list = models.Comment.objects.filter(article_id=nid).select_related('reply')
    #文章阅读数加一
    obj =models.Article.objects.get(nid=nid)
    obj.read_count +=1
    obj.save()

    #获取文章列表
    article = models.Article.objects.filter(blog=blog, nid=nid).select_related('category', 'articledetail').first()

    #获取最新评论
    recent_comments = models.Comment.objects.all().order_by("-nid")[0:5]

    response = render(
        request,
        'home_detail.html',
        {
            'blog': blog,
            'article': article,
            'comment_list': comment_list,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'recent_comments': recent_comments,
        }

    )
    return response


def article_updown(request):
    result = {'status': False, 'message': None, 'data': {}}
    user_session_message = request.session.get("user_info")
    #用户已登录情况

    if user_session_message:
        result['status'] = True
        #获取提交的数据
        nid = request.POST.get('nid')
        message = request.POST.get('message')
        print nid,message
        #获取当前文章点赞数和踩数。
        article_obj = models.Article.objects.filter(nid=nid)
        up_count = article_obj.first().up_count
        down_count = article_obj.first().down_count
        #获取当前文章赞或踩表格对象。
        updown_obj =models.UpDown.objects.filter(article_id = nid,user_id = user_session_message["nid"]).first()
        #如果当前文章已被踩或赞
        if updown_obj:
            #如果文章是已被赞
            if updown_obj.up:
                article_obj.update(up_count =up_count-1)
                updown_obj.delete()
                if message == "down":
                    article_obj.update(down_count=down_count + 1)
                    models.UpDown.objects.create(article_id=nid, user_id=user_session_message["nid"], up=False)
            #文章已被踩
            else:
                article_obj.update(down_count=down_count-1)
                updown_obj.delete()
                if message == "up":
                    article_obj.update(up_count=up_count + 1)
                    models.UpDown.objects.create(article_id=nid, user_id=user_session_message["nid"], up=True)
        #文章没有被踩或赞
        else:
            #判断当前文章是赞还是踩
            if message == "up":
                article_obj.update(up_count=up_count+1)
                models.UpDown.objects.create(article_id =nid,user_id =user_session_message["nid"],up =True)
            else:
                article_obj.update(down_count=down_count+1)
                models.UpDown.objects.create(article_id = nid,user_id = user_session_message["nid"],up =False)
        #返回文章赞数和踩数
        result['data']["up_count"] = article_obj.first().up_count
        result['data']["down_count"] = article_obj.first().down_count
        print up_count,down_count
        return HttpResponse(json.dumps(result))
    else:
        return HttpResponse(json.dumps(result))


        #修改文章表点赞或点踩


def submit_comment(request):

    result = {'status': False, 'message': None, 'data': {}}
    user_session_message = request.session.get("user_info")
    # 获取文章nid,被回复的评论的nid,回复内容
    artcle_nid = request.POST.get("article_nid")
    reply_comment_nid =request.POST.get("reply_comment_nid")
    reply_comment = request.POST.get("reply_comment")
    comment_user =request.POST.get("comment_user")
    #将评论写进文章评论表

        #如果该条评论是回复他人的评论。
    if reply_comment_nid:
        comment_user='@'+comment_user #拼接字符串
        reply_comment =reply_comment.replace(comment_user,"")
        models.Comment.objects.create(content=reply_comment,
                                            article_id=artcle_nid,
                                            user_id=user_session_message["nid"],                                            reply_id=reply_comment_nid,)
    else:
        models.Comment.objects.create(content=reply_comment,
                                      article_id=artcle_nid,
                                      user_id=user_session_message["nid"],
                                      )
    #文章评论数自增一
    article_obj =models.Article.objects.get(nid=artcle_nid)
    article_obj.comment_count +=1
    article_obj.save()
    result["status"] = True
    return HttpResponse(json.dumps(result))


def delete_comment(request):
    result = {'status': False, 'message': None, 'data': {}}
    reply_comment_nid = request.POST.get("reply_comment_nid")
    artcle_nid = request.POST.get("article_nid")
    #删除评论
    try:
        models.Comment.objects.filter(nid =reply_comment_nid).delete()
        #文章表评论数自减一
        article_obj = models.Article.objects.get(nid=artcle_nid)
        article_obj.comment_count -= 1
        result['data']['comment_counts']=article_obj.comment_count
        article_obj.save()
        result['status'] = True
    except:
        result['status'] = False
    return HttpResponse(json.dumps(result))

web/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render,HttpResponse
from django.shortcuts import redirect
from repository import models
from utils.pagination import Pagination
from django.urls import reverse
import json
from django.http.request import QueryDict
def index(request, *args, **kwargs):
    """
    博客首页，展示全部博文
    :param request:
    :return:
    """
    article_type_list = models.Article.type_choices
    # [
    #     (1, "Python"),
    #     (2, "Linux"),
    #     (3, "OpenStack"),
    #     (4, "GoLang"),
    # ]
    if kwargs:
        #kwargs ={'article_type_id':'xx'}
        article_type_id = int(kwargs['article_type_id'])
        base_url = reverse('index',kwargs=kwargs)
    else:
        article_type_id = None
        base_url = '/'

    data_count = models.Article.objects.filter(**kwargs).count()
    #获取所有文章数
    page_obj = Pagination(request.GET.get('p'),data_count)
    #实例化分页对象，request.GET.get('p') 获取当前连接的当前页码
    article_list = models.Article.objects.filter(**kwargs).order_by('-nid')[page_obj.start:page_obj.end]
    #获取文章对象列表
    page_str = page_obj.page_str(base_url)
    #获取分页html

    #吐血推荐文章对象
    tuxue_articles = models.Article.objects.all().order_by("-up_count")[0:8]

    #评论最多文章对象
    comments_article = models.Article.objects.all().order_by("-comment_count")[0:8]


    return render(
        request,
        'index.html',
        {

            'article_type_id': article_type_id,
            'article_type_list': article_type_list,
            'article_list': article_list,
            'page_str': page_str,
            'tuxue_articles':tuxue_articles,
            'comments_article':comments_article,
        }
    )

templates/backend_article.html
{% extends 'backend_layout.html' %}
{% load search %}
{% block css %}
<style>
    .conditions a{
        display: inline-block;
        padding: 2px 5px;
        margin-left: 5px;
    }
    .conditions a.active{
        background-color: #b35215;
        color: #ffffff;
    }
</style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">文章列表</li>
    </ol>
    <div>

        <div style="border: 1px dashed #dddddd;padding: 8px;border-left: 3px solid #337ab7;">
            <i class="fa fa-search" aria-hidden="true"></i> 搜索条件
        </div>
        <div style="padding: 10px">
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% article_type_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% article_type_combine type_list arg_dict %}
                </div>
            </div>
            <div class="conditions row clearfix" style="margin: 0;padding: 8px 0;">
                <div class="col-xs-1" style="text-align: right">
                    {% category_all arg_dict %}
                </div>
                <div class="col-xs-11">
                    {% category_combine category_list arg_dict %}
                </div>
            </div>

        </div>
        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0" >
            <i class="fa fa-table" aria-hidden="true"></i>
            <div id = "search_count" style="display: inline-block">搜索文章({{ data_count }}篇)</div>
            <a target="_blank" href="/backend/add-article.html" class="right"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建新文章
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>文章标题</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr >
                    <td><a href="/blog/{{ row.blog.site }}/{{ row.nid }}.html">{{ row.title }}</a></td>
                    <td>
                        <a class="btn btn-danger btn-xs" id = "{{ row.nid }}" onclick="Delete(event);">
                            <i class="fa fa-times" aria-hidden="true" ></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/backend/edit-article-{{ row.nid }}.html">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        function Delete(event) {
            var nid =  event.target.id;
            console.log(nid);
            $.ajax({

                url: "/backend/delete-article.html",

                data: {nid: nid},

                type: 'POST',

                success: function (redata) {
                    var obj = jQuery.parseJSON(redata);
                    if (obj.status){
                        $(event.target).parent().parent().remove(); //删除标签
                        $("#search_count").text("搜索文章({%  minus_self data_count %}篇)");
                    }


                }

            });


        }
    </script>

{% endblock %}

templates/backend_index.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
   <h1>欢迎登陆：{{ request.session.user_info.nickname }}</h1>
{% endblock %}

{% block js %}

{% endblock %}

templates/home.html
{% extends 'home_layout.html' %}

{% block content %}
        {% for row in article_list %}
       <div class="day">
            <div class="postTitle">
                <a id="homepage1_HomePageDays_ctl00_DayList_TitleUrl_0" class="postTitle2" href="/blog/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
            </div>
            <div class="postCon">
                <div class="c_b_p_desc">{{ row.summary }}<a href="/blog/{{ blog.site }}/{{ row.nid }}.html" class="c_b_p_desc_readmore">阅读全文</a></div>
            </div>
            <div class="clear"></div>
            <div class="postDesc">posted @ {{ row.create_time|date:"Y-m-d H:i:s" }}  阅读({{ row.read_count }}) 评论({{ row.comment_count }}) <a href="/backend/edit-article-{{ row.nid }}.html" rel="nofollow">编辑</a></div>
            <div class="clear"></div>
            <div class="postSeparator"></div>
        </div>
    {% endfor %}
    {{ page_str }}
{% endblock %}

templates/home_layout.html
{% load get_number %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>博客园</title>
    <link type="text/css" rel="stylesheet" href="/static/css/blog-common.css">
    <link id="MainCss" type="text/css" rel="stylesheet" href="/static/css/bundle-SimpleBlue.css">
    <link type="text/css" rel="stylesheet" href="/static/css/133379.css">
    <link id="mobile-style" media="only screen and (max-width: 768px)" type="text/css" rel="stylesheet" href="/static/css/bundle-SimpleBlue-mobile.css">
    {% block css %}{% endblock %}
    <style>
        .hide{
            display: none;
        }
    </style>
</head>

<body>
    <a name="top"></a>
    <div id="home">
        <div id="header">
            <div id="blogTitle">
                <!--done-->
                <div class="title"><a id="Header1_HeaderTitle" class="headermaintitle" href="">{{ blog.title }}</a></div>
                <div class="subtitle">{{blog.subtitle}}</div>
            </div>
            <!--end: blogTitle 博客的标题和副标题 -->
            <div id="navigator">
                <ul id="navList">
                    <li id="nav_sitehome"><a id="blog_nav_sitehome" class="menu" href="/">博客首页</a></li>
                    <li id="nav_myhome"><a id="blog_nav_myhome" class="menu" href="/blog/{{ blog.site }}.html">个人首页</a></li>
                    <li id="nav_admin"><a id="blog_nav_admin" class="menu" rel="nofollow" href="/backend/index.html">管理</a></li>
                </ul>
                <div class="blogStats">
                    <div id="blog_stats">
                        <!--done-->
                        文章-{{ article_counts }}&nbsp; 评论-{{ article_comment_counts }}&nbsp;
                    </div>
                </div>
                <!--end: blogStats -->
            </div>
            <!--end: navigator 博客导航栏 -->
        </div>
        <!--end: header 头部 -->
        <div id="main">
            <div id="mainContent">
                <div class="forFlow">
                    <!--done-->
                    {% block content %}{% endblock %}

                </div>
                <!--end: forFlow -->
            </div>
            <!--end: mainContent 主体内容容器-->
            <div id="sideBar">
                <div id="sideBarMain">
                    <!--done-->
                    <div class="newsItem">
                        <h3 class="catListTitle">公告</h3>
                        <div id="blog-news">
                            <h4 style="padding-top:10px">{{ blog.ad }}</h4>
                            <div id="profile_block">昵称：<a href="/blog/{{ blog.site }}.html">{{blog.user.nickname}}</a>
                                <br>邮箱：<a href="" title="">{{ blog.user.email }}</a>
                                <br>粉丝：<a href="">{{ blog.user.fans.count }}</a>
                                <br>关注：<a href="">{{ blog.user.f.count }}</a>
                                <div id="p_b_follow"><a href="" onclick="follow()">+加关注</a></div>
                            </div>
                        </div>
                    </div>
                    <div id="leftcontentcontainer">
                        <div id="blog-sidecolumn">
                            <div id="sidebar_search" class="sidebar-block"></div>
                            <div id="sidebar_toptags" class="sidebar-block">
                                <div class="catListTag">
                                    <h3 class="catListTitle">我的标签</h3>
                                    <ul>
                                        {% for tag in tag_list %}
                                        <li><a href="/blog/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <div id="sidebar_categories">
                                <div class="catListPostCategory">
                                    <h3 class="catListTitle">随笔分类</h3>
                                    <ul>
                                    {% for tag in category_list %}
                                    <li><a href="/blog/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                                    {% endfor %}
                                    </ul>
                                </div>
                                <div class="catListPostArchive">
                                    <h3 class="catListTitle">随笔档案</h3>
                                    <ul>
                                        {% for tag in date_list %}
                                        <li><a id="CatList_LinkList_1_Link_0" href="/blog/{{ blog.site }}/date/{{ tag.ctime }}.html">{{ tag.ctime}}({{ tag.num}})</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <div id="sidebar_scorerank" class="sidebar-block">
                            </div>
                            <div id="sidebar_recentcomments" class="sidebar-block">
                                <div id="recent_comments_wrap">
                                    <div class="catListComment">
                                        <h3 class="catListTitle">最新评论</h3>
                                        {% for item in recent_comments %}
                                        <div id="RecentCommentsBlock">
                                            <ul>
                                                {% if item.reply %}
                                                <li class="recent_comment_title"><a href="/blog/{{ item.article.blog.site }}/{{ item.article.nid }}.html#{{ item.nid }}">{% get_number_index item recent_comments %}. {{ item.article.title }}</a></li>
                                                <li class="recent_comment_body">@{{ item.reply.user.nickname }}{{ item.content|safe }}</li>
                                                <li class="recent_comment_author">--{{ item.user.nickname }}</li>
                                                    {% else %}
                                                <li class="recent_comment_title"><a href="/blog/{{ item.article.blog.site }}/{{ item.article.nid }}.html#{{ item.nid }}">{% get_number_index item recent_comments %}. {{ item.article.title }}</a></li>
                                                <li class="recent_comment_body">{{ item.content|safe }}</li>
                                                <li class="recent_comment_author">--{{ item.user.nickname }}</li>
                                                    {% endif %}

                                            </ul>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end: sideBarMain -->
            </div>
            <!--end: sideBar 侧边栏容器 -->
            <div class="clear"></div>
        </div>
        <!--end: main -->
        <div class="clear"></div>
        <div id="footer">
            <!--done-->
            Copyright ©2017 陈津龙
        </div>
        <!--end: footer -->
    </div>
    <!--end: home 自定义的最大容器 -->

    <script async="" src="/static/js/analytics.js" type="text/javascript"></script>
    <script src="/static/js/blog-common.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    {% block js %}{% endblock %}
</body>

</html>